// Real Chromium against an isolated web build. All API traffic uses synthetic fixtures.
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {initialNodes,emptyAmount,cloneActiveNodes,cloneSourceCounts,loadProgress} from '../../../packages/domain/dist/index.js';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({executablePath:process.env.BROWSER_BINARY,headless:true});
const origin='http://127.0.0.1:3100',id='11111111-1111-4111-8111-111111111111',branchId='123456789012345678901234',otherBranch='abcdefabcdefabcdefabcdef';
try{for(const [width,height] of [[1440,900],[1280,720],[1024,768],[768,1024],[390,844]]){
 const context=await browser.newContext({viewport:{width,height}}),page=await context.newPage();await page.clock.setFixedTime(new Date('2026-09-23T12:00:00Z'));
 const branches=[{id:branchId,name:'Sucursal destino',active:true,startDate:'2020-01-01T03:00:00Z'},{id:otherBranch,name:'Sucursal histórica con nombre largo para revisar la copia de valores entre sucursales',active:false,startDate:'2020-01-01T03:00:00Z'}];
 const nodes=initialNodes([],randomUUID);nodes.push({nodeId:randomUUID(),code:randomUUID(),kind:'ITEM',name:'Digitales',parentId:nodes[0].nodeId,position:0,amount:{...emptyAmount(),state:'CARGADO',input:'5+5',value:'10.00'},quantity:{state:'CARGADO',value:'0'}});
 const original={schemaVersion:1,structureVersion:1,initializedAt:'2026-08-01T12:00:00Z',initializedBy:'fixture',nodes};
 const sourceRows=[{id:randomUUID(),branchId,branchName:branches[0].name,year:2026,month:8,loadStatus:'CARGADO',initialized:true,categories:0,items:1,loadedAmounts:1,sameBranch:true,samePeriod:false},{id:randomUUID(),branchId:otherBranch,branchName:branches[1].name,year:2026,month:9,loadStatus:'CARGADO',initialized:true,categories:0,items:1,loadedAmounts:1,sameBranch:false,samePeriod:true}];
 let row={id,revision:0,note:null,structure:null,progress:loadProgress([])},created=false,pending=null,fail=0,incompatible=false,role='EDITOR',writes=0,previews=0;const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin===origin)return route.continue();if(url.origin!=='http://localhost:3001'){errors.push('Unexpected external '+url.origin);return route.abort();}const headers={'access-control-allow-origin':origin,'access-control-allow-credentials':'true','access-control-allow-methods':'GET,POST,PATCH,OPTIONS','access-control-allow-headers':'content-type'};if(request.method()==='OPTIONS')return route.fulfill({status:204,headers});const path=url.pathname;let body,status=200;
 if(request.method()!=='GET'){const input=request.postDataJSON();await new Promise(r=>setTimeout(r,350));if(fail){status=fail;fail=0;body={message:status===409?'El origen cambió. Generá una nueva vista previa.':'Error simulado, podés reintentar.'};}else if(path==='/eerr'){created=true;writes++;body={id,branchId,year:2026,month:9,loadStatus:'SIN_CARGAR',createdAt:'2026-09-23T12:00:00Z'};}else if(path.endsWith('/clone/preview')){previews++;pending=input;const source=sourceRows.find(r=>r.id===input.sourceEerrId);body={source,destination:{id,branchId,branchName:branches[0].name,year:2026,month:9},mode:input.mode,counts:cloneSourceCounts(nodes),destinationCategories:0,compatible:!incompatible,issues:incompatible?['Categoría requerida ausente: Ventas históricas']:[],seedTemplate:true,crossBranchWarning:input.mode==='ESTRUCTURA_Y_VALORES'&&!source.sameBranch?'Estás por copiar valores desde otra sucursal. Los importes y cantidades pueden no representar la operación del destino.':null,included:input.mode==='ESTRUCTURA'?['Estructura e ítems activos']:['Estructura, importes, expresiones y cantidades'],excluded:['Notas de ítem y nota general','Archivados','Actores y timestamps del origen','Cálculos derivados'],revisions:{source:5,destination:0,template:null},previewToken:incompatible?null:'offline-preview',expiresAt:'2026-09-23T12:05:00Z'};}else if(path.endsWith('/clone/confirm')){assert.equal(input.sourceEerrId,pending.sourceEerrId);assert.equal(input.mode,pending.mode);if(input.mode==='ESTRUCTURA_Y_VALORES'&&input.sourceEerrId===sourceRows[1].id)assert.equal(input.confirmCrossBranchValues,true);writes++;const copied=cloneActiveNodes(original,input.mode,randomUUID);row={...row,revision:1,structure:{...original,nodes:copied,initializedBy:'new'},progress:loadProgress(copied)};body=row;}else if(path.endsWith('/structure/initialize')){writes++;row={...row,revision:1,structure:{...original,nodes:initialNodes([],randomUUID)}};body=row;}else {errors.push('Unexpected write '+path);return route.abort();}}
 else if(path==='/auth/me')body={user:{name:'Persona',isAdmin:false,branchAccesses:[{branchId,role},{branchId:otherBranch,role:'READER'}]}};
 else if(path==='/branches')body=branches;
 else if(path===`/eerr/${id}`)body={id,branchId,year:2026,month:9,loadStatus:'SIN_CARGAR',createdAt:'2026-09-23T12:00:00Z'};
 else if(path===`/eerr/${id}/structure`)body=row;
 else if(path===`/eerr/${id}/clone-sources`)body=sourceRows;
 else if(path==='/eerr')body=created?[{id,branchId,year:2026,month:9,loadStatus:'SIN_CARGAR',createdAt:'2026-09-23T12:00:00Z'}]:[];
 else {errors.push('Unexpected API '+path);return route.abort();}return route.fulfill({status,json:body,headers});});
 const dialog=page.getByRole('dialog'),close=async()=>{await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});};
 const shot=async label=>{await page.screenshot({path:join(tmpdir(),`ep04c1-${width}-${label}.png`),fullPage:true});const box=await dialog.boundingBox();if(box)assert.ok(box.x>=-1&&box.y>=-1&&box.x+box.width<=width+1&&box.y+box.height<=height+1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));};
 await page.goto(`${origin}/eerr`);await page.getByRole('button',{name:'Crear período',exact:true}).click();await page.getByRole('button',{name:'Confirmar creación',exact:true}).click();await page.waitForURL(`${origin}/eerr/${id}`);await page.getByRole('button',{name:'Clonar estructura',exact:true}).waitFor();assert.equal(writes,1);assert.equal(row.structure,null);assert.equal(previews,0);
 await page.getByRole('button',{name:'Clonar estructura y valores',exact:true}).click();await dialog.getByLabel('EERR origen').locator('option').nth(1).waitFor({state:'attached'});assert.equal(await dialog.getByLabel('EERR origen').inputValue(),sourceRows[0].id);await shot('selection');await close();assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Clonar estructura y valores');
 await page.getByRole('button',{name:'Clonar estructura y valores',exact:true}).click();await dialog.getByLabel('EERR origen').selectOption(sourceRows[1].id);fail=500;await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByRole('alert').waitFor();assert.equal(await dialog.getByLabel('EERR origen').inputValue(),sourceRows[1].id);await shot('error');
 incompatible=true;await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByText('No se puede clonar',{exact:true}).waitFor();assert.ok(await dialog.getByRole('button',{name:'Confirmar clonación',exact:true}).isDisabled());await shot('incompatible');
 await dialog.getByRole('button',{name:'Volver a elegir origen'}).click();incompatible=false;await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByRole('checkbox').waitFor();assert.ok(await dialog.getByRole('button',{name:'Confirmar clonación',exact:true}).isDisabled());await dialog.getByRole('checkbox').check();await shot('preview');assert.equal(writes,1);
 fail=409;await dialog.getByRole('button',{name:'Confirmar clonación',exact:true}).click();await dialog.getByText('Se conservaron el modo y el origen.',{exact:false}).waitFor();assert.equal(await dialog.getByLabel('EERR origen').inputValue(),sourceRows[1].id);assert.equal(await dialog.getByLabel('Modo de clonación').inputValue(),'ESTRUCTURA_Y_VALORES');await shot('conflict');
 await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByRole('checkbox').waitFor();assert.equal(await dialog.getByRole('checkbox').isChecked(),false);await dialog.getByRole('checkbox').check();const before=writes;await dialog.getByRole('button',{name:'Confirmar clonación',exact:true}).click();assert.ok(await dialog.getByRole('button',{name:'Clonando…',exact:true}).isDisabled());await dialog.waitFor({state:'hidden'});assert.equal(writes,before+1);await page.getByRole('button',{name:'Acciones de Digitales',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Clonar estructura',exact:true}).count(),0);assert.match(await page.locator('main').innerText(),/10,00 ARS/);
 row={id,revision:0,note:null,structure:null,progress:loadProgress([])};role='READER';await page.reload();await page.getByText('Estructura sin preparar',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:/Clonar|Usar estructura base/}).count(),0);assert.deepEqual(errors,[]);
 await context.close();console.log(`PASS clone ${width}x${height}: creación separada, selección, error, incompatibilidad, advertencia, 409, confirmación, foco, permisos y geometría`);
}}finally{await browser.close();}
