// Isolated Chromium, all API traffic intercepted; no Nest/Atlas/bootstrap.
import { emptyAnalysis } from "./browser-analysis-fixture.mjs";
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {initialNodes,emptyAmount,loadProgress,completePendingPlan} from '../../../packages/domain/dist/index.js';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({executablePath:process.env.BROWSER_BINARY,headless:true});
const origin='http://127.0.0.1:3100',id='11111111-1111-4111-8111-111111111111',branchId='123456789012345678901234';
try{for(const [width,height] of [[1440,900],[1280,720],[1024,768],[768,1024],[390,844]]){
 const context=await browser.newContext({viewport:{width,height}}),page=await context.newPage();await page.clock.setFixedTime(new Date('2026-09-23T12:00:00Z'));
 const nodes=initialNodes([],randomUUID);for(let i=0;i<3;i++)nodes.push({nodeId:randomUUID(),code:randomUUID(),kind:'ITEM',name:['Digitales','Pendiente con nombre largo para revisar el resumen en pantallas pequeñas','Archivado'][i],parentId:nodes[0].nodeId,position:i,amount:emptyAmount(),quantity:{state:'SIN_CARGAR',value:null},note:'Nota conservada',...(i===2?{archive:{state:'ARCHIVED',at:'2026-09-01T12:00:00Z',by:'fixture'}}:{})});
 let row={id,revision:5,note:'General conservada',structure:{schemaVersion:1,structureVersion:1,initializedAt:'2026-09-01T12:00:00Z',initializedBy:'fixture',nodes},progress:loadProgress(nodes)},role='EDITOR',conflict=false,writes=0,previews=0;const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.origin===origin)return route.continue();if(url.origin!=='http://localhost:3001'){errors.push('Unexpected '+url.origin);return route.abort();}const headers={'access-control-allow-origin':origin,'access-control-allow-credentials':'true','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'};if(req.method()==='OPTIONS')return route.fulfill({status:204,headers});let body,status=200;const path=url.pathname;
 if(req.method()==='POST'){await new Promise(r=>setTimeout(r,350));const input=req.postDataJSON();if(path.endsWith('/complete-pending/preview')){assert.deepEqual(input,{});previews++;const plan=completePendingPlan(row.structure);delete plan.changes;body={...plan,destination:{id,branchId,branchName:'Sucursal ficticia',year:2026,month:9},revision:row.revision,previewToken:plan.affected.length?'fixture-preview':null,expiresAt:'2026-09-23T12:05:00Z'};}else if(path.endsWith('/complete-pending/confirm')){assert.deepEqual(input,{previewToken:'fixture-preview'});if(conflict){status=409;body={message:'El EERR cambió. Generá un nuevo preview.'};conflict=false;}else{const plan=completePendingPlan(row.structure);for(const c of plan.changes)row.structure.nodes.find(n=>n.nodeId===c.nodeId).amount=c.amount;row.revision++;row.progress=loadProgress(row.structure.nodes);writes++;body={result:row,affectedItems:plan.changes.length};}}else{errors.push('Unexpected write '+path);return route.abort();}}
 else if(path==='/auth/me')body={user:{name:'Persona',isAdmin:false,branchAccesses:[{branchId,role}]}};
 else if(path==='/branches')body=[{id:branchId,name:'Sucursal ficticia',active:false,startDate:'2020-01-01T03:00:00Z'}];
 else if(path===`/eerr/${id}`)body={id,branchId,year:2026,month:9,loadStatus:row.progress.status};
 else if(path.endsWith('/structure'))body=row;
 else if(path.endsWith('/analysis'))body=emptyAnalysis(row,id);
 else{errors.push('Unexpected API '+path);return route.abort();}return route.fulfill({status,json:body,headers});});
 const dialog=page.getByRole('dialog',{name:'Completar pendientes con cero'}),open=async()=>{await page.getByRole('button',{name:'Acciones de estructura',exact:true}).click();await page.getByRole('menuitem',{name:'Completar pendientes con cero',exact:true}).click();};
 const shot=async label=>{await page.screenshot({path:join(tmpdir(),`ep04c3-${width}-${label}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const box=await dialog.boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1);};
 await page.goto(`${origin}/eerr/${id}`);await page.getByRole('button',{name:'Editar importe de Digitales',exact:true}).click();const input=page.getByRole('textbox',{name:'Importe o expresión · Digitales',exact:true});await input.fill('123');await open();await dialog.getByText('Hay borradores sin guardar.',{exact:false}).waitFor();assert.equal(await dialog.getByRole('button',{name:'Generar vista previa'}).count(),0);assert.equal(previews,0);await shot('draft');await dialog.getByRole('button',{name:'Volver a los borradores'}).click();assert.equal(await input.inputValue(),'123');await input.press('Escape');
 await open();await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByRole('button',{name:'Completar con cero',exact:true}).waitFor();await dialog.locator('summary').click();assert.match(await dialog.innerText(),/2 importes se convertirán en cero/);assert.doesNotMatch(await dialog.innerText(),/Archivado/);assert.match(await dialog.innerText(),/No modificará cantidades ni cerrará el período/);await shot('preview');assert.equal(writes,0);
 await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Acciones de estructura');
 await open();await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByRole('button',{name:'Completar con cero',exact:true}).waitFor();conflict=true;await dialog.getByRole('button',{name:'Completar con cero',exact:true}).click();await dialog.getByText('La vista previa está desactualizada.',{exact:false}).waitFor();assert.match(await dialog.innerText(),/2 importes se convertirán en cero/);assert.ok(await dialog.getByRole('button',{name:'Completar con cero',exact:true}).isDisabled());await shot('conflict');
 await dialog.getByRole('button',{name:'Actualizar vista previa'}).click();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Completar con cero')?.disabled);await dialog.getByRole('button',{name:'Completar con cero',exact:true}).click();assert.ok(await dialog.getByRole('button',{name:'Completando…',exact:true}).isDisabled());await page.keyboard.press('Escape');assert.ok(await dialog.isVisible());await dialog.waitFor({state:'hidden'});assert.equal(writes,1);const item=page.locator(`tr[data-node-id="${nodes[3].nodeId}"]`);assert.match(await item.innerText(),/0,00 ARS/);assert.equal(row.structure.nodes[3].amount.input,null);assert.equal(row.structure.nodes[3].quantity.state,'SIN_CARGAR');assert.equal(await page.getByRole('progressbar',{name:'Progreso de importes'}).evaluate(p=>p.value/p.max),1);
 await open();await dialog.getByRole('button',{name:'Generar vista previa'}).click();await dialog.getByText('No hay importes pendientes.',{exact:false}).waitFor();assert.ok(await dialog.getByRole('button',{name:'Completar con cero',exact:true}).isDisabled());await shot('noop');await page.keyboard.press('Escape');assert.equal(writes,1);
 role='READER';await page.reload();await page.getByRole('button',{name:'Descargar plantilla',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Acciones de estructura',exact:true}).count(),0);assert.deepEqual(errors,[]);await context.close();console.log(`PASS completar ${width}x${height}: borradores, preview, 409, no-op, cantidades, foco, Escape, permisos y geometría`);
}}finally{await browser.close();}
